name: flutter_sequencer
version: 0.5.0
description: >-
  A Flutter plugin for sequencing audio. Use it to build sequences of notes and play them back using
  SFZ or SF2 sound fonts.
repository: https://github.com/mikeperri/flutter_sequencer

environment:
  sdk: '>=3.11.5 <4.0.0'
  flutter: ">=3.41.9"

dependencies:
  ffi:
  flutter:
    sdk: flutter
  path:
  plugin_platform_interface:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.michaeljperri.flutter_sequencer
        pluginClass: FlutterSequencerPlugin
      ios:
        pluginClass: FlutterSequencerPlugin
